# Generated by Django 5.0.6 on 2024-06-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_fundwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundwallet',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2022-08-09T14:21:32.000Z'),
            preserve_default=False,
        ),
    ]
